### ISSUE TITLE
Installation Django 1.8.5

### ISSUE THREAD

**Issue by mykljohn** [voxy/django-audio-recorder#4]
I'm having trouble getting this to work on Python 2.7 Django 1.8.5  Thanks for any help.

pip install creates the dist_info folder but nothing else  (django_audio_recorder-0.0.0.dist-info/)

I get the following log: note the warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

running install
running bdist_egg
running egg_info
creating django_audio_recorder.egg-info
writing requirements to django_audio_recorder.egg-info/requires.txt
writing django_audio_recorder.egg-info/PKG-INFO
writing top-level names to django_audio_recorder.egg-info/top_level.txt
writing dependency_links to django_audio_recorder.egg-info/dependency_links.txt
writing manifest file 'django_audio_recorder.egg-info/SOURCES.txt'
reading manifest file 'django_audio_recorder.egg-info/SOURCES.txt'
writing manifest file 'django_audio_recorder.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
**warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install**
creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying django_audio_recorder.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_audio_recorder.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_audio_recorder.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_audio_recorder.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_audio_recorder.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/django_audio_recorder-0.0.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing django_audio_recorder-0.0.0-py2.7.egg
Removing /home/mykl/.virtualenvs/django18/lib/python2.7/site-packages/django_audio_recorder-0.0.0-py2.7.egg
Copying django_audio_recorder-0.0.0-py2.7.egg to /home/mykl/.virtualenvs/django18/lib/python2.7/site-packages
django-audio-recorder 0.0.0 is already the active version in easy-install.pth
Installed /home/mykl/.virtualenvs/django18/lib/python2.7/site-packages/django_audio_recorder-0.0.0-py2.7.egg
Processing dependencies for django-audio-recorder==0.0.0
Searching for Django==1.8
Best match: Django 1.8
Processing Django-1.8-py2.7.egg
Django 1.8 is already the active version in easy-install.pth
Installing django-admin.py script to /home/mykl/.virtualenvs/django18/bin
Installing django-admin script to /home/mykl/.virtualenvs/django18/bin
Using /home/mykl/.virtualenvs/django18/lib/python2.7/site-packages/Django-1.8-py2.7.egg
Finished processing dependencies for django-audio-recorder==0.0.0

**Comment by massover** [comment]
I never actually got around to pushing to pypi or using this in production. You can try pip installing directly from github:

pip install git+https://github.com/voxy/django-audio-recorder.git#egg=django-audio-recorder

**Comment by mykljohn** [comment]
Thanks...I think that worked at least for the install portion :)

I want to add it as a button or field on the Django Admin screen for one of my models.  Is that possible?  do you have an example of this?
